#!/bin/sh

test -e  $HOME/.config/xfce4/xfconf/xfce-perchannel-xml/displays.xml  &&  rm  $HOME/.config/xfce4/xfconf/xfce-perchannel-xml/displays.xml

DVI=$(xrandr | grep " connected" | grep DVI | cut -d" " -f1)
VGA=$(xrandr | grep " connected" | grep VGA | cut -d" " -f1)
xrandr --output $VGA --mode 1024x768 --pos 0x0 --rotate normal --output $DVI --mode 1024x768 --pos 0x0 --rotate normal --same-as $VGA

exit 0
