#!/bin/bash

set -e

HDMI_STATUS=$(</sys/class/drm/card0/card0-HDMI-A-1/status )
USER=$(w| grep xfce4-session | cut -d' ' -f1)

if [ "connected" == "$HDMI_STATUS" ]; then
    su $USER -c "/usr/bin/resolucion_aio"
    su $USER -c "/usr/bin/audio_aio"
fi

