#!/bin/bash

sleep 3

test -e $HOME/.config/xfce4/xfconf/xfce-perchannel-xml/displays.xml && rm $HOME/.config/xfce4/xfconf/xfce-perchannel-xml/displays.xml

RESOLUTION="1920x1080"

MAIN=$(xrandr  | grep " connected"  | grep -v "disconnected" | grep "VGA" | cut -d" " -f1)
SECONDARY=$(xrandr  | grep " connected"  | grep -v "disconnected" | grep "HDMI" | cut -d" " -f1)

if ! xrandr | grep "$MAIN" | grep -q "$RESOLUTION"; then
   xrandr --addmode $MAIN "$RESOLUTION"
fi

if [ -n "$MAIN" ] && [ -n "$SECONDARY" ]; then
   xrandr --output $MAIN --mode $RESOLUTION --pos 0x0 --rotate normal --output $SECONDARY --mode $RESOLUTION --pos 0x0 --rotate normal --same-as $MAIN
fi

exit 0
